FROM rrdockerhub/alpine-arm32v7 as builder

RUN apk update && \
	apk add alpine-sdk 

ADD . /app

WORKDIR /app/src

RUN make

FROM armhf/alpine

COPY --from=builder /app/src/led_trigger /usr/bin/led_trigger
COPY --from=builder /app/docker-entrypoint.sh /usr/bin

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["led_trigger", "led0", "heartbeat"]
